### ISSUE TITLE
Incorrect method call for getting user with email

### ISSUE THREAD

**Issue by Gambitier** [REAN-Foundation/reancare-service#9]
**Describe the bug**
Incorrect method call for fetching user with email on line number 84

https://github.com/REAN-Foundation/reancare-service/blob/73d97d60fd842ff070da1bc35cb9ea9e675b36c6/src/services/user.service.ts#L73-L89

**To Reproduce**
- N/A

**Expected behavior**
code should should be 
```
person = await this._personRepo.getPersonWithEmail(otpDetails.Email);
```

**Screenshots**
- N/A

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
- N/A

**Comment by kiran-rean** [comment]
Fixed. Thanks Akash for pointing this out.
